name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        cython: [true, false]

    steps:
    - uses: actions/checkout@v2
    - name: Install libnetfilter-queue-dev
      run: sudo apt-get install libnetfilter-queue-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install cython
      run: |
        pip install cython
      if: ${{ matrix.cython }}
    - name: Install package
      run: |
        pip install .
    - name: Import
      run: |
        python -c "import netfilterqueue"
